spring.application.name=BankAccount

# Database connection credentials
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password

# Jpa settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# console h2 seeting
spring.h2.console.enable=true
spring.h2.console.path=/h2-console


#security login details
app.security.admin-user=bank_admin
app.security.admin-password=bank_admin_01